---
- name: Populating projects variables in HTML
  hosts: localhost
  connection: local
  vars_files:
    - data/container.yaml
    - data/automation.yaml
    - data/cloud.yaml
    - data/monitoring.yaml
    - data/security.yaml
    - data/learning.yaml
  tasks:
    - name: Creating project HTML page from template
      template:
        src: templates/project.html
        dest: _site/projects.html
